name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.20"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgl1-mesa-glx \
            libglib2.0-0 \
            libgtk-3-0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyQt6 via pip
        run: |
          python -m pip install PyQt6 PyQt6-WebEngine

      - name: Build executables
        run: |
          pyinstaller --onefile --windowed --icon=search.png -n 'Bundle Browser' --add-data="search.png:." BrowseBundlesUtil.py -y
          pyinstaller --onefile --windowed -n 'Add bundles' addBundlesUI.py -y
          pyinstaller --onefile --windowed -n 'College Browser' CollegeBrowserUtil.py -y

      - name: Set executable permissions
        run: |
          chmod +x dist/Bundle\ Browser
          chmod +x dist/Add\ bundles
          chmod +x dist/College\ Browser

      - name: Create GitHub Release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        with:
          tag_name: "v2.0.4"
          release_name: "CD Unit Bundles Manager v2.0"
          body: "Prod release"
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            dist/Bundle\ Browser
            dist/Add\ bundles
            dist/College\ Browser
