name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.6"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgl1-mesa-glx \
            libglib2.0-0 \
            libgtk-3-0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyQt6 via pip
        run: |
          python -m pip install PyQt6 PyQt6-WebEngine

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --icon=search.png -n 'Bundle Browser' --add-data="search.png:." BrowseBundlesUtil.py -y

      - name: Upload executable
        uses: actions/upload-artifact@v3 # Latest version
        with:
          name: Bundle Browser
          path: dist/Bundle\ Browser
