name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.20"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgl1-mesa-glx \
            libglib2.0-0 \
            libgtk-3-0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyQt6 via pip
        run: |
          python -m pip install PyQt6 PyQt6-WebEngine

      - name: Build executables
        run: |
          pyinstaller --onefile --windowed --icon=search.png -n 'Bundle Browser' --add-data="search.png:." BrowseBundlesUtil.py -y
          pyinstaller --onefile --windowed -n 'Add bundles' addBundlesUI.py -y
          pyinstaller --onefile --windowed -n 'College Browser' CollegeBrowserUtil.py -y

      - name: Set executable permissions
        run: |
          chmod +x dist/Bundle\ Browser
          chmod +x dist/Add\ bundles
          chmod +x dist/College\ Browser

      - name: Upload to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          body: |
            Production Release
          draft: false
          prerelease: false
          make_latest: true
          release_name: "v2.0 Prod release"
